### ISSUE TITLE
Unknown keyword :service

### ISSUE THREAD

**Issue by htachib** [ryanckulp/10k_hours#21]
![Screen Shot 2023-01-25 at 2 43 56 PM](https://user-images.githubusercontent.com/16859709/214676351-ba3c1fa4-e43c-4813-80cb-573f1a36f8b8.png)

I was able to successfully launch an instance, thanks for making it!!

Only line of code to add in `Post` model - syntax is not recognized. Another note is to run `rails db:seed`.

**Comment by ryanckulp** [comment]
did you add the `:amazon` block to your `config/storage.yml` before changing this line of code (Line 9)? if so, i'll adjust how the service is selected to be in the `environments` code vs an option on the Model.

re `db:seed`, step 5 of the README (`rails db:setup`) should also run `db:seed`, let me know if maybe you didn't follow that step.

**Comment by htachib** [comment]
yep, block is
```
amazon:
  service: S3
  access_key_id: <%= ENV['AMAZON_S3_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['AMAZON_S3_SECRET'] %>
  region: us-east-1
  bucket: tachifigures-<%= Rails.env %>
```

I did run rails db:setup but perhaps I had other issues. I ended up just
manually creating a Project and User myself in rails console.
